### PR TITLE
Edit CSS into one file, add icons, new font, readd backgrounds.

### PR DESCRIPTION
**Pull request by josephan**
Hey Andrew, sorry it took me a while to contribute. I've been pretty bummed out recently. Any ways just give me your thoughts about the changes, it isn't much but I thought I would clean it up much more. If it's too simple and you don't want to merge it, I understand. I chose Braum's passive as a logo and definitely like the theme around him. I think he's one of the most fun supports to play and a very strong pick. I will definitely add more contributions in the near future. Maybe I can start adding images you took on the Facebook to the website on a slider or something.

### CODE REVIEW

**Comment by KlotzAndrew** [comment]
Message received, I'll take a look tomorrow - logo looks awesome


Sent by Outlook for Android





On Sun, Oct 18, 2015 at 4:19 PM -0700, "Joseph An" <notifications@github.com> wrote:
Hey Andrew, sorry it took me a while to contribute. I've been pretty bummed out recently. Any was just give me your thoughts about the changes, it isn't much but I thought I would clean it up much more. If it's too simple and you don't want to merge it, I understand. I chose Braum's passive as a logo and definitely like the theme around him. I think he's one of the most fun supports to play and a very strong pick. I will definitely add more contributions in the near future. Maybe I can start adding images you took on the Facebook to the website on a slider or something.
You can view, comment on, or merge this pull request online at:

  https://github.com/KlotzAndrew/hero-queue/pull/1

-- Commit Summary --

  * Edit CSS into one file, add icons and new font

-- File Changes --

    A app/assets/images/brand-logo.png (0)
    A app/assets/images/favicon.png (0)
    M app/assets/stylesheets/application.scss (7)
    A app/assets/stylesheets/custom.css.scss (28)
    M app/assets/stylesheets/scaffolds.scss (11)
    M app/assets/stylesheets/static_pages.scss (42)
    M app/assets/stylesheets/teams.scss (12)
    M app/assets/stylesheets/tournaments.scss (92)
    M app/views/layouts/_header.html.erb (7)
    M app/views/layouts/application.html.erb (2)
    M app/views/static_pages/home.html.erb (11)
    M app/views/summoners/index.html.erb (4)
    M app/views/tournaments/index.html.erb (4)

-- Patch Links --

https://github.com/KlotzAndrew/hero-queue/pull/1.patch
https://github.com/KlotzAndrew/hero-queue/pull/1.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/KlotzAndrew/hero-queue/pull/1

**Comment by josephan** [comment]
The font is from Google fonts, the favicon and logo I created myself by tracing over Braum's passive. For the aligned text I didn't seem to notice and misaligned text from the pages I had access to. If you let me know where the errors occured I can definitely fix them. Also I removed the wallpaper because I thought it would be much simpler. However if you want something in the background to make it less stale than we can look for another one. Or if you just wan to keep the wallpapers it's fine.

**Comment by KlotzAndrew** [comment]
Cool, definitely needs to stay colourful though - especially for an esports page. Easiest is keep the previous background. tournaments#show and teams#show pages are not showing css formatting, did it get copied over?

**Comment by josephan** [comment]
OK I will update it with the wallpaper and fix the css for tournaments#show and teams#show and reissue the pull request tomorrow. If I find a nice wallpaper I'll run it by you.

**Comment by josephan** [comment]
Hey I updated this pull request. Tell me what you think, I put the background and transparency back in. The styling of the tournaments#show and teams#show is fixed.

**Comment by KlotzAndrew** [comment]
Looks way better! few things still
* no need for erb in css files, assets are already getting precompiled before deploy 
* Could swap the navbar to inverse & switch the logo from black to white? It looks like most of the popular eSports sites tend to have very dark backgrounds contrasted with bright buttons/logos (http://www.dotabuff.com, http://www.lolking.net, http://2ez.gg, http://wardscore.loltools.net, http://na.op.gg, http://victoriousgaming.com). Thoughts?
* favicon looks like it has slightly bevelled corners with a white background, possible to switch to square corners or transparent background like the logo?

Other than that it looks good, nearly ready to merge it to master

**Comment by josephan** [comment]
I added the erb for the css because instead of directly using the url of the wallpaper I used asset_path so that it allows fingerprinting so the image can be cached. It basically improves the performance so it doesn't query the server every time for the same wallpaper.

My honest opinion is that it looks better with the white header as it fits with the footer. But I don't think it really matters. The best web app right now for League is definitely op.gg and they have light blue and white color schemes. Maybe it stands out more? I'm not sure it's your decision.

I agree, I'll change the favicon to black with transparent backgrounds.

**Comment by KlotzAndrew** [comment]
sprokets already adds the fingerprint when they are precompiled, right? Adding erb into css makes it way harder for a designer to get involved (they need to know an additional language on top of css), I want to avoid that if possible :p

It looks like the common theme is a darker background contrasted with much lighter text for buttons. Most common is black/grey background with white buttons. op.gg is still a stong blue background contrasted with white buttons, same contrast theme with a slightly less dark backdrop. I think bootstrap inverse with white buttons keeps in line with dark back and bright buttons, while a white navbar with black buttons would seem to be the odd one out. Want to skype about the design this weekend?

**Comment by josephan** [comment]
Hey I changed it back to the original version. It looks a lot better.

**Comment by KlotzAndrew** [comment]
merged!

**Pull request merged**
